############# English navigation ##############

# main menu
[[main]]
name = "Products"
url = "/products"
weight = 1

[[main]]
name = "Consulting"
url = "/consulting"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

# footer menu
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 1

[[footer]]
name = "Terms of Service"
url = "/terms-of-service"
weight = 2

[[footer]]
name = "Support"
url = "/support"
weight = 3
